services:
  mysql:
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080